[package]
name = "vtebench"
version = "0.1.1"
license = "Apache-2.0"
authors = ["Joe Wilm <joe@jwilm.com>"]
description = "Benchmark terminal emulators"
documentation = "https://docs.rs/vtebench"
repository = "https://github.com/jwilm/vtebench"

[dependencies]
structopt = "0.1"
structopt-derive = "0.1"
terminfo = "0.4"
failure = "0.1"
rand = "0.4"
